import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AuthProvider } from './auth/AuthContext'
import { ToastProvider } from './ui/Toast'
import ErrorBoundary from './components/ErrorBoundary'
import { initTheme } from './lib/theme'
import './styles.css'

// Apply persisted theme BEFORE first paint so dark-mode users don't see a
// brief flash of the light palette. initTheme() is idempotent and synchronous.
initTheme()

// Register service worker for PWA (auto-update mode).
// The virtual module is generated by vite-plugin-pwa at build time;
// in dev mode it's a no-op.
import { registerSW } from 'virtual:pwa-register'
registerSW({ immediate: true })

// -----------------------------------------------------------------------------
// Global async error nets.
//
// React's <ErrorBoundary> only catches *render-time* exceptions. A rejected
// promise from an event handler, a setTimeout callback that throws, or a
// network call whose error isn't awaited will all silently surface as red
// console noise without any user feedback. We attach two listeners here so
// such cases at least get logged with a uniform tag and (optionally) reported
// to a sink configured via VITE_ERROR_SINK_URL. Failures of the report itself
// are swallowed — we never let telemetry break the app.
// -----------------------------------------------------------------------------
function reportAsyncError(kind, payload) {
  try {
    // eslint-disable-next-line no-console
    console.error(`[global:${kind}]`, payload)
    const sink = import.meta.env?.VITE_ERROR_SINK_URL
    if (!sink || typeof navigator === 'undefined' || !navigator.sendBeacon) return
    const body = JSON.stringify({
      kind,
      message: payload?.message || String(payload),
      stack: payload?.stack || null,
      url: typeof location !== 'undefined' ? location.href : null,
      ts: Date.now(),
    })
    navigator.sendBeacon(sink, new Blob([body], { type: 'application/json' }))
  } catch (_) {
    /* never let the reporter throw */
  }
}

if (typeof window !== 'undefined') {
  window.addEventListener('unhandledrejection', (e) => {
    reportAsyncError('unhandledrejection', e?.reason)
  })
  window.addEventListener('error', (e) => {
    reportAsyncError('window.error', e?.error || e?.message)
  })
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode data-qoder-id="qel-react-strictmode-961901f1" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-react-strictmode-961901f1&quot;,&quot;filePath&quot;:&quot;react-vite/src/main.jsx&quot;,&quot;componentName&quot;:&quot;Unknown&quot;,&quot;elementRole&quot;:&quot;react-strictmode&quot;,&quot;loc&quot;:{&quot;line&quot;:8,&quot;column&quot;:3}}">
    <ErrorBoundary>
      <BrowserRouter data-qoder-id="qel-browserrouter-79960d47" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-browserrouter-79960d47&quot;,&quot;filePath&quot;:&quot;react-vite/src/main.jsx&quot;,&quot;componentName&quot;:&quot;Unknown&quot;,&quot;elementRole&quot;:&quot;browserrouter&quot;,&quot;loc&quot;:{&quot;line&quot;:9,&quot;column&quot;:5}}">
        <AuthProvider data-qoder-id="qel-authprovider-5ed10292" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-authprovider-5ed10292&quot;,&quot;filePath&quot;:&quot;react-vite/src/main.jsx&quot;,&quot;componentName&quot;:&quot;Unknown&quot;,&quot;elementRole&quot;:&quot;authprovider&quot;,&quot;loc&quot;:{&quot;line&quot;:11,&quot;column&quot;:7}}">
          <ToastProvider data-qoder-id="qel-toastprovider-e2c65499" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-toastprovider-e2c65499&quot;,&quot;filePath&quot;:&quot;react-vite/src/main.jsx&quot;,&quot;componentName&quot;:&quot;Unknown&quot;,&quot;elementRole&quot;:&quot;toastprovider&quot;,&quot;loc&quot;:{&quot;line&quot;:13,&quot;column&quot;:9}}">
            <App  data-qoder-id="qel-app-de45d070" data-qoder-source="{&quot;qoderId&quot;:&quot;qel-app-de45d070&quot;,&quot;filePath&quot;:&quot;react-vite/src/main.jsx&quot;,&quot;componentName&quot;:&quot;Unknown&quot;,&quot;elementRole&quot;:&quot;app&quot;,&quot;loc&quot;:{&quot;line&quot;:10,&quot;column&quot;:7}}"/>
          </ToastProvider>
        </AuthProvider>
      </BrowserRouter>
    </ErrorBoundary>
  </React.StrictMode>
)
